### ISSUE TITLE
DTXClient standalone

### ISSUE THREAD

**Issue by neildufva** [troybowman/dtxmsg#1]
Awesome presentation and repo... is it possible to change the DTX Client standalone code so it doesnt have to require IDA and the sdk? I'd just like to communicate with the Instruments server without IDA. Any help is appreciated!

**Comment by troybowman** [comment]
It is very possible, though I don't know if I will have time to do it.

It seems the client code only relies on the IDA SDK for the qstring and bytevec_t classes. STL has basically the equivalent of those, with std::string and std::vector<uint8_t>. Try copying dtxmsg_common.(cpp,h) and dtxmsg_client.(cpp,h) to somewhere else, and replace all instances of qstring with std::string and all instances of bytevec_t with std::vector<uint8_t> (of course, they don't have the exact same behavior so you may have to massage it a little).

I bet it's easier than you think!

**Comment by neildufva** [comment]
Thanks Troy. I appreciate the help. I’ve got everything converted over but I’m having issues with make channel. I’ve got preform handshake working great but make channel is always coming back with a -1 / err being shown as broken pipe. I’ve checked the code so many times now but I’m out of ideas. Hoping you might have some insight

**Comment by neildufva** [comment]
Actually I take that back... my send message seems to be wrong because the instruments server seems to always send the capabilities and channels regardless even if I don’t send any message and just call receive... the issue is probably in my send message then but still don’t know what the issue is. 

Do you know how many bytes the messages you typically send are? 

I wonder if using an NSData or mutabaledata would cause problems vs using an std::vector

**Comment by neildufva** [comment]
Actually never mind, got it working... had to stay completely c++
Something must be different with how objective C is packing bytes or order. Thanks Troy

**Comment by troybowman** [comment]
Glad you got it working! Let me know if you spot any issues :)

**Comment by Dantee296** [comment]
@neildufva ll you be able to share your working ?
coz i m also looking for DTX Client standalone code. 
To make it work without IDA
Thanks

**Comment by Dantee296** [comment]
@neildufva @troybowman hi i need help in some areas , i have converted project but stuck at some places
