### ISSUE TITLE
DTXClient with std::string ,  std::vector<uint8_t>

### ISSUE THREAD

**Issue by Dantee296** [troybowman/dtxmsg#2]
hi , do you have some time to convert this tool IDA independent  
or can you help me to  convert it into standalone project.

by using std::string and std::vector<uint8_t>

**Comment by Dantee296** [comment]
void append_v(std::vector<uint8_t> &out, const void *v, size_t len)
{
 // stuck here , dont know how to convert void * to  const std::vector<uint8_t> 
}

**Comment by Dantee296** [comment]
@troybowman  hi i need help in some areas , i have converted project but stuck at some places

**Comment by Dantee296** [comment]
@Dantee296 @

**Comment by Dantee296** [comment]
any help guys ?

**Comment by troybowman** [comment]
Hello, sorry for the long delay.

It seems like a standalone Instruments client would be quite popular, so I plan to fully implement one. This will be an entirely different project - separate from dtxmsg, implemented entirely in c++, and can be built and run on its own.

So essentially I plan to split this dtxmsg repo into two repos, one for the plugin (which is mostly only useful for reference), and one for the dtxmsg_client. I imagine the standalone client repo will be more useful to more people.

Expect an update soon!

**Comment by Dantee296** [comment]
awesome!

**Comment by Dantee296** [comment]
@troybowman any news

**Comment by Dantee296** [comment]
@troybowman when we x

**Comment by Dantee296** [comment]
@troybowman any update sir ?

**Comment by Dantee296** [comment]
@troybowman when we are expecting this update Sir.
Thanks

**Comment by troybowman** [comment]
I have created a new repo: https://github.com/troybowman/ios_instruments_client

This app should be able to build + run on any recent OSX version, without any dependency on the IDA SDK.

Let me know if it works for you!

**Comment by Dantee296** [comment]
@troybowman works like a charm!! 
Thanks Alot! 
God bless you Sir!
