### ISSUE TITLE
ida7.0 how to compile it?

### ISSUE THREAD

**Issue by yhnu** [troybowman/dtxmsg#3]

**Comment by troybowman** [comment]
The plugin was released after IDA 7.1, so 7.0 is not officially supported.

Still, I imagine you could make some simple adjustments to get it to compile (but I can't guarantee that it will run perfectly).

What specific errors are you getting?

**Comment by yhnu** [comment]
![image](https://user-images.githubusercontent.com/23090916/71390771-8507de00-263c-11ea-867e-9bd186338ad8.png)

**Comment by yhnu** [comment]
> The plugin was released after IDA 7.1, so 7.0 is not officially supported.
> 
> Still, I imagine you could make some simple adjustments to get it to compile (but I can't guarantee that it will run perfectly).
> 
> What specific errors are you getting?

![image](https://user-images.githubusercontent.com/23090916/71390783-8fc27300-263c-11ea-9892-7d34e6222ea0.png)

**Comment by troybowman** [comment]
My apologies, I misled you. The plugin depends on the decompiler microcode, which was published in version 7.1: https://www.hex-rays.com/products/ida/7.1/index.shtml.

It is not possible to build the plugin with IDA 7.0, you must update to 7.1 or later.

**Comment by yhnu** [comment]
> My apologies, I misled you. The plugin depends on the decompiler microcode, which was published in version 7.1: https://www.hex-rays.com/products/ida/7.1/index.shtml.
> 
> It is not possible to build the plugin with IDA 7.0, you must update to 7.1 or later.

appreciate your help.i just want to know how to send message to iphone to get the memgraphic
![image](https://user-images.githubusercontent.com/23090916/71419408-4f014300-26aa-11ea-9680-8b995d122d56.png)

https://developer.apple.com/videos/play/wwdc2018/416/
